apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
  namespace: postgres
data:
  POSTGRES_DB: postgresdb
  POSTGRES_USER: **USERNAME**
  POSTGRES_PASSWORD: **PASSWORD**